### ISSUE TITLE
Create GET requests

### ISSUE THREAD

**Issue by jbosire** [vanlyfe/capstone#34]
As a backend developer, I want to create sufficient GET requests so that I can access all the data in my database when required

DESCRIPTION
GET requests must be defined in their respective route files and the methods declared in their respective model classes to facilitate accessing data

A/C

- [ ] Listings GET routes :
      - GET ("/") -  Returns all listings in the database
      - GET ("/user/:userId") - Returns all the listings for a particular user
      -  GET ("/:listingId") - Returns one particular listing by its id
      - GET ("/best") - Returns the 4 best rated listings
 
- [ ] Auth GET routes :
      - GET("/me") - Returns details of the currently logged in user

- [ ] Orders GET routes:
      - GET ("/") - Returns all the orders in the database
      - GET ("/user/:userId") - Returns all the orders for a particular user
      - GET ("/:orderId") - Returns one particular order by its id
- [ ] Ratings GET routes:
      - GET ("/:listingId") - Returns ratings for one particular listing by calculating the average of all ratings given for that listing
- [ ] Reviews GET routes: 
      - GET ("/:listingId") - Returns all the reviews for a particular listing

DoD

All the GET requests have been created and are working when tested on an api platform such as postman
