### ISSUE TITLE
Create POST requests

### ISSUE THREAD

**Issue by jbosire** [vanlyfe/capstone#35]
As a backend developer, I want to create sufficient POST requests so that I can store data in my database

DESCRIPTION
POST requests must be defined in their respective route files and the methods declared in their respective model classes to facilitate storing data

A/C

- [ ] Listings POST routes 
      - POST ("/") -  Stores a new listing in the database
 
- [ ] Auth POST routes :
      - POST("/login") - Logs in an existing user
      - POST("/register") - Registers a new user and stores the details in the database

- [ ] Orders POST routes:
      - POST ("/") - Creates and stores a new order in the database
    
- [ ] Ratings POST routes:
      - POST("/:listingId") - Creates a new rating for a listing
      
- [ ] Reviews POST routes: 
      - POST ("/:listingId") - Creates a new review for a listing

DoD

All the POST requests have been created and are working when tested on an api platform such as postman
