### ISSUE TITLE
Create PUT requests

### ISSUE THREAD

**Issue by jbosire** [vanlyfe/capstone#36]
As a backend developer, I want to create sufficient PUT requests so that I can update data in my database

DESCRIPTION
PUT requests must be defined in their respective route files and the methods declared in their respective model classes to facilitate updating data

A/C

- [ ] Listings PUT routes 
      - PUT ("/:listingId") -  Updates a particular listing in the database
 
- [ ] Auth PUT routes :
      - PUT("/:userId") - updates an existing user profile
      
- [ ] Reviews PUT routes: 
      - PUT ("/:reviewId") - Updates an existing listing review

DoD

All the PUT requests have been created and are working when tested on an api platform such as postman
