### ISSUE TITLE
Create DELETE requests

### ISSUE THREAD

**Issue by jbosire** [vanlyfe/capstone#37]
As a backend developer, I want to create sufficient DELETE requests so that I can delete data in my database

DESCRIPTION
DELETE requests must be defined in their respective route files and the methods declared in their respective model classes to facilitate deleting data

A/C

- [ ] Listings DELETE routes 
      - DELETE ("/:listingId") -  Deletes an existing listing in the database
 
- [ ] Auth DELETE routes :
      - DELETE("/:userId") - Deletes a user profile
      
- [ ] Reviews DELETE routes: 
      - DELETE ("/:reviewId") - Deletes a review from the database

DoD

All the DELETE requests have been created and are working when tested on an api platform such as postman
