### ISSUE TITLE
Initialize react project frontend

### ISSUE THREAD

**Issue by ammar-fakih** [vanlyfe/capstone#4]
- [x] As a fr dev, I want the react project to be created so that I can begin implementing features.

- [x] As a fr dev, I want the necessary dependencies to be defined in the project.json file so that I can use them to add features.

- [x] As a fr dev, I want the initial jsx files to be created so that I can see the structure of the project.
