### ISSUE TITLE
Create Listing

### ISSUE THREAD

**Issue by ammar-fakih** [vanlyfe/capstone#74]
- [x] Listing Page front-end form outline #72 
- [x] Save listing page to server #119 
- [ ] Post Images to Server #120
