### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by jbosire** [vanlyfe/capstone#91]
DESCRIPTION
As a backend developer, I want to have sufficient unit tests to ensure all the declared methods and routes are functioning as expected

A/C

BACKEND
- [ ] app.test.js 
- [ ] config.test.js 

MODELS
- [ ] listing.test.js
- [ ] order.test.js
- [ ] rating.test.js
- [ ] review.test.js
- [ ] user.test.js

ROUTES
- [ ] auth.test.js
- [ ] listings.test.js
- [ ] orders.test.js
- [ ] ratings.test.js
- [ ] reviews.test.js

MIDDLEWARE

- [ ] permissions.test.js
- [ ] security.test.js

TESTS

- [ ] common.js
- [ ] createListings.js
- [ ] createUsers.js
- [ ] createOrders.js
- [ ] createRatings.js
- [ ] createReviews.js

UTILS

- [ ] tokens.test.js

DoD
All the files are created and tests defined within them to handle at least 90% of all methods and cases.
